### PR TITLE
Make it compatible with Rails@7.1.2

### PR DESCRIPTION
**Pull request by Joerg-Seitz**

### CODE REVIEW

**Comment by simi** [comment]
Have you resolved this in any other way @Joerg-Seitz?

**Comment by willfish** [comment]
@simi This is working for us https://github.com/trade-tariff/routing-filter/blob/master/lib/routing_filter/adapters/routers/journey.rb

**Comment by willfish** [comment]
Sadly the lack of responsiveness here made us self-solve in a fork

**Comment by simi** [comment]
I'm happy to help you to merge this, it would solve https://github.com/svenfuchs/routing-filter/issues/83 as well. But this project got a little outdated, there is missing CI and so on. Would you mind to help resolving those problems?

**Comment by willfish** [comment]
I'm happy to open a PR - I've fixed it for our team already.

**Pull request closed without merging**
