### PR TITLE
Feature/rails 5

### LINKED ISSUE #59: Is there a plan to support Rails 5 ?
Hello,

Thanks for you work on this gems!

Do you know if there is a plan to support Rails 5?

:)

### PR DESCRIPTION
**Pull request by bricesanchez**
Should fix #59

### CODE REVIEW

**Comment by simi** [comment]
Is this Rails 5 only change?

**Comment by bricesanchez** [comment]
I think it should works on rails 4.2 too

**Comment by simi** [comment]
:heart:

**Comment by simi** [comment]
Feel free to test master and ping me if everything is ok. I can release new version.

**Pull request merged**
