### PR TITLE
Rails 5.2

### PR DESCRIPTION
**Pull request by nebolsin**
- [x] Support [Rails 5.2.0](http://weblog.rubyonrails.org/2018/4/9/Rails-5-2-0-final/)
- [x] Add Ruby 2.5.1 to the build matrix on Travis

/cc @simi

### CODE REVIEW

**Comment by kevin-jj** [comment]
@simi @svenfuchs @bricesanchez  Please merge this PR and roll our a new release that we can upgrade rails 5.2. Thanks a lot.

**Comment by kevin-jj** [comment]
@nebolsin  Can this PR  remove the upper bound in rails version?

**Comment by johnnyshields** [comment]
@simi please merge

**Comment by simi** [comment]
done https://rubygems.org/gems/routing-filter/versions/0.6.2

**Pull request merged**
